import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { afterEach, expect, it, vi } from 'vitest';
import { measurePilotUpload, PilotUploadCheck, uploadPilotSample } from '../src/pilot-upload-check.js';
import { checkPilotMetadata } from '../src/pilot-preflight-checks.js';
import { runPilotPreflight, MEDIA_CHECKS } from '../src/pilot-preflight.js';

afterEach(() => vi.useRealTimers());
const signal = () => new AbortController().signal;
const result = () => ({ kbps: 40_000, checkedAt: new Date().toISOString(), bytes: 2 * 1024 ** 2 });
async function endpoint(handler: (request: IncomingMessage, response: ServerResponse) => void) {
  const server = createServer(handler);
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const address = server.address();
  if (!address || typeof address === 'string') throw new Error('Missing address');
  return { url: new URL(`http://127.0.0.1:${address.port}/up`), close: async () => {
    server.closeAllConnections(); await new Promise<void>((resolve) => server.close(() => resolve()));
  } };
}

it('uploads only generated bytes and measures through the complete server acknowledgement', async () => {
  let length = 0; let authorization: string | undefined; let cookie: string | undefined;
  const local = await endpoint((request, response) => {
    authorization = request.headers.authorization; cookie = request.headers.cookie;
    request.on('data', (data: Buffer) => { length += data.length; });
    request.on('end', () => setTimeout(() => response.end('ok'), 35));
  });
  try {
    expect(await uploadPilotSample(256 * 1024, signal(), local.url)).toBeGreaterThanOrEqual(30);
    expect(length).toBe(256 * 1024); expect(authorization).toBeUndefined(); expect(cookie).toBeUndefined();
  } finally { await local.close(); }
});

it('does not follow redirects, accept excessive responses or upload to an arbitrary endpoint', async () => {
  let requests = 0;
  const local = await endpoint((request, response) => {
    requests += 1; request.resume(); request.on('end', () => {
      if (request.url === '/up') response.writeHead(302, { Location: '/redirected' }).end();
      else response.end(Buffer.alloc(32_768));
    });
  });
  try {
    await expect(uploadPilotSample(32, signal(), local.url)).rejects.toThrow();
    expect(requests).toBe(1);
    await expect(uploadPilotSample(32, signal(), new URL('/large', local.url))).rejects.toThrow();
    await expect(uploadPilotSample(32, signal(), new URL('https://example.com/up'))).rejects.toThrow();
  } finally { await local.close(); }
});

it('closes a stalled real upload when the operator cancels', async () => {
  const local = await endpoint((request) => request.resume());
  const controller = new AbortController();
  try {
    const upload = uploadPilotSample(1_024, controller.signal, local.url);
    const rejected = expect(upload).rejects.toThrow();
    controller.abort(); await rejected;
  } finally { await local.close(); }
});

it('ramps up to at most 26 MiB, uses wall time and stops when a sample spans one second', async () => {
  const fast = vi.fn(async () => 100);
  const measured = await measurePilotUpload(signal(), fast);
  expect(fast.mock.calls).toHaveLength(3);
  expect(measured.bytes).toBe(26 * 1024 ** 2);
  expect(measured.kbps).toBe(16 * 1024 ** 2 * 8 / 100);
  const slow = vi.fn(async () => 2_000);
  expect((await measurePilotUpload(signal(), slow)).kbps).toBe(2 * 1024 ** 2 * 8 / 2_000);
  expect(slow).toHaveBeenCalledOnce();
});

it('aborts stalled measurements within twelve seconds and never credits an unconfirmed sample', async () => {
  vi.useFakeTimers();
  let probeSignal: AbortSignal | undefined;
  const measured = measurePilotUpload(signal(), async (_bytes, probe) => {
    probeSignal = probe;
    return new Promise<number>((_resolve, reject) => probe.addEventListener('abort', () => reject(new Error('Timeout')), { once: true }));
  });
  const rejected = expect(measured).rejects.toThrow();
  await vi.advanceTimersByTimeAsync(12_000); await rejected;
  expect(probeSignal?.aborted).toBe(true);
});

it('shares one upload across courts, preserves its age and never tests with a live output', async () => {
  vi.useFakeTimers();
  const measurement = result();
  const probe = vi.fn(async () => measurement);
  const shared = new PilotUploadCheck(probe);
  expect(await Promise.all([shared.get(signal(), false), shared.get(signal(), false), shared.get(signal(), false)]))
    .toEqual([measurement, measurement, measurement]);
  expect(probe).toHaveBeenCalledOnce();
  await vi.advanceTimersByTimeAsync(240_000);
  expect(await shared.get(signal(), true, true)).toEqual(measurement);
  await vi.advanceTimersByTimeAsync(60_000);
  expect(await shared.get(signal(), true)).toBeNull();
  expect(probe).toHaveBeenCalledOnce();
  await shared.get(signal(), false); expect(probe).toHaveBeenCalledTimes(2);
});

it('cancels only after the last waiting court leaves and aborts immediately when an output starts', async () => {
  const signals: AbortSignal[] = [];
  const shared = new PilotUploadCheck(async (probe) => {
    signals.push(probe);
    return new Promise((_resolve, reject) => {
      probe.addEventListener('abort', () => reject(new Error('Aborted')), { once: true });
      if (probe.aborted) reject(new Error('Aborted'));
    });
  });
  const one = new AbortController(); const two = new AbortController();
  const first = expect(shared.get(one.signal, false)).rejects.toThrow();
  const second = expect(shared.get(two.signal, false)).rejects.toThrow();
  await Promise.resolve(); one.abort(); await first;
  expect(signals[0]?.aborted).toBe(false);
  two.abort(); await second; expect(signals[0]?.aborted).toBe(true);
  const third = expect(shared.get(signal(), false)).rejects.toThrow();
  await Promise.resolve(); shared.cancel(); await third;
  expect(signals[1]?.aborted).toBe(true);
});

it('forces a new network test and does not reuse the old success after a failed repeat', async () => {
  const probe = vi.fn(async () => result());
  const shared = new PilotUploadCheck(probe);
  await shared.get(signal(), false);
  probe.mockRejectedValueOnce(new Error('Offline'));
  await expect(shared.get(signal(), false, true)).rejects.toThrow();
  expect(await shared.get(signal(), true)).toBeNull();
});

it('compares combined video and audio with 30 percent headroom and retains cached measurement age', async () => {
  const checkedAt = new Date(Date.now() - 240_000).toISOString();
  const context = {
    source: { id: 'synthetic' as const, kind: 'synthetic' as const, label: 'Prueba' }, mode: 'youtube' as const, mobile: null,
    assertMatch: async () => undefined, host: async () => ({ cores: 4, cpuBusyRatio: 0, availableMemoryBytes: 1e9, totalMemoryBytes: 2e9, availableStorageBytes: 1e9 }),
    destination: async () => ({ broadcastStatus: 'ready', streamStatus: 'ready', healthStatus: 'good' }),
    transport: async () => ({ milliseconds: 4, encrypted: true }), mediaMtx: async () => true,
    upload: async () => ({ ...result(), checkedAt }), uploadDemand: { kbps: 3 * (6_000 + 128), courts: 3 },
  };
  expect(await checkPilotMetadata('network', context)).toMatchObject({ status: 'pass', checkedAt });
  const blocked = await checkPilotMetadata('network', { ...context, upload: async () => ({ ...result(), kbps: 23_000 }) });
  expect(blocked.status).toBe('blocked'); expect(blocked.message).toContain('23.9 Mbps');
  expect((await checkPilotMetadata('network', { ...context, upload: async () => null })).status).toBe('warning');
  const report = await runPilotPreflight({ signal: signal(), onUpdate: () => undefined,
    metadata: async (id) => id === 'network' ? checkPilotMetadata(id, context) : { status: 'pass', message: 'OK' },
    media: async () => ({ checks: Object.fromEntries(MEDIA_CHECKS.map((id) => [id, { status: 'pass', message: 'OK' }])),
      preview: { url: '/api/pilot/sessions/test', durationSeconds: 10, sizeBytes: 1_000 } }),
  });
  expect(report.validUntil).toBe(new Date(Date.parse(checkedAt) + 300_000).toISOString());
});
