import { randomBytes } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { request as httpRequest } from 'node:http';

const ENDPOINT = 'https://speed.cloudflare.com/__up';
const LIFETIME = 5 * 60_000;
export type PilotUploadMeasurement = { readonly kbps: number; readonly checkedAt: string; readonly bytes: number };

/** Only generated bytes leave the runtime. No redirects, credentials, media or telemetry. */
export async function uploadPilotSample(bytes: number, signal: AbortSignal, target = new URL(ENDPOINT)): Promise<number> {
  signal.throwIfAborted();
  if (target.href !== ENDPOINT && !(target.protocol === 'http:' && target.hostname === '127.0.0.1')) {
    throw new Error('Invalid upload measurement endpoint');
  }
  const body = randomBytes(bytes);
  return new Promise((resolve, reject) => {
    const started = performance.now();
    const request = (target.protocol === 'https:' ? httpsRequest : httpRequest)(target, {
      method: 'POST', signal, agent: false,
      headers: { 'Content-Type': 'application/octet-stream', 'Content-Length': bytes, 'Cache-Control': 'no-store' },
    });
    request.on('error', () => reject(new Error('No se pudo medir la subida.')));
    request.on('response', (response) => {
      let received = 0;
      response.on('error', () => reject(new Error('Respuesta de subida incompleta.')));
      response.on('data', (data: Buffer) => {
        received += data.length;
        if (received > 16_384) {
          reject(new Error('Respuesta de subida demasiado grande.'));
          request.destroy(); response.destroy();
        }
      });
      response.on('end', () => {
        const milliseconds = performance.now() - started;
        if (response.statusCode !== 200 || !request.writableFinished || received > 16_384 || milliseconds <= 0) {
          request.destroy(); reject(new Error('La prueba de subida no fue confirmada.')); return;
        }
        resolve(milliseconds);
      });
    });
    request.end(body);
  });
}

/** At most 26 MiB / 12 seconds, including all ramp-up samples. Wall time is deliberately conservative. */
export async function measurePilotUpload(signal: AbortSignal,
  sample: typeof uploadPilotSample = uploadPilotSample): Promise<PilotUploadMeasurement> {
  const controller = new AbortController();
  const abort = () => controller.abort();
  signal.addEventListener('abort', abort, { once: true });
  if (signal.aborted) abort();
  const timer = setTimeout(abort, 12_000); timer.unref();
  const checkedAt = new Date().toISOString();
  let totalBytes = 0;
  try {
    for (const bytes of [2, 8, 16].map((mib) => mib * 1024 ** 2)) {
      controller.signal.throwIfAborted();
      const milliseconds = await sample(bytes, controller.signal);
      controller.signal.throwIfAborted();
      if (!Number.isFinite(milliseconds) || milliseconds < 10) throw new Error('La muestra de subida es demasiado breve.');
      totalBytes += bytes;
      if (milliseconds >= 1_000 || bytes === 16 * 1024 ** 2) return { kbps: bytes * 8 / milliseconds, checkedAt, bytes: totalBytes };
    }
    throw new Error('No upload sample');
  } finally { clearTimeout(timer); signal.removeEventListener('abort', abort); }
}

/** Concurrent courts share one test; cancelling one court must not cancel the others. */
export class PilotUploadCheck {
  private latest: PilotUploadMeasurement | null = null;
  private generation = 0;
  private pending: { controller: AbortController; task: Promise<PilotUploadMeasurement>; users: number } | null = null;
  public constructor(private readonly measure: typeof measurePilotUpload = measurePilotUpload) {}

  public get revision(): number { return this.generation; }

  public cancel(): void { this.pending?.controller.abort(); }

  public async get(signal: AbortSignal, live: boolean, force = false): Promise<PilotUploadMeasurement | null> {
    signal.throwIfAborted();
    const age = this.latest ? Date.now() - Date.parse(this.latest.checkedAt) : Infinity;
    if ((!force || live) && age >= 0 && age < LIFETIME) return this.latest;
    if (live) return null;
    if (force) this.latest = null;
    if (!this.pending || this.pending.controller.signal.aborted) {
      const controller = new AbortController();
      const pending = { controller, users: 0, task: Promise.resolve().then(() => this.measure(controller.signal)) };
      this.pending = pending;
      void pending.task.then((result) => {
        if (!controller.signal.aborted) { this.latest = result; this.generation += 1; }
      }, () => undefined).finally(() => { if (this.pending === pending) this.pending = null; });
    }
    const pending = this.pending;
    pending.users += 1;
    try {
      return await new Promise<PilotUploadMeasurement>((resolve, reject) => {
        const abort = () => { cleanup(); reject(new Error('Comprobación de subida cancelada.')); };
        const cleanup = () => signal.removeEventListener('abort', abort);
        signal.addEventListener('abort', abort, { once: true });
        void pending.task.then((result) => { cleanup(); resolve(result); }, (error: unknown) => { cleanup(); reject(error); });
        if (signal.aborted) abort();
      });
    } finally {
      pending.users -= 1;
      if (pending.users === 0) pending.controller.abort();
    }
  }
}
